# Grah Theory - Adjacency Matrix

Calculate number of different paths

In [1]:
import numpy as np

## Example 1: Matrix^2 = Matrix * Matrix 

In [8]:
m1 = np.matrix([[1,0,1],
                [0,1,1],
                [1,0,0]])
m1

matrix([[1, 0, 1],
        [0, 1, 1],
        [1, 0, 0]])

In [9]:
m2 = m1*m1
m2

matrix([[2, 0, 1],
        [1, 1, 1],
        [1, 0, 1]])

In [97]:
m4 = m2*m2
m4

matrix([[5, 0, 3],
        [4, 1, 3],
        [3, 0, 2]])

## Example 2: Matrix^2 = matrix * matrix, and Matrix^4 = Matrix^2 * Matrix^2

In [2]:
m = np.matrix([[0, 1, 0, 1, 1],
               [0, 0, 1, 0, 1],
               [1, 1, 0, 1, 0],
               [0, 0, 0, 0, 1],
               [0, 0, 0, 1, 0]])
m

matrix([[0, 1, 0, 1, 1],
        [0, 0, 1, 0, 1],
        [1, 1, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0]])

In [10]:
m2 = m*m
np.sum(m2)


16

In [5]:
## Counter number of paths with length of 2
np.sum(m2)

16

In [6]:
## Counter number of paths with length of 4
m4 = m2*m2
print(m4)
np.sum(m4)

[[0 1 1 2 5]
 [1 1 1 5 2]
 [1 2 1 4 6]
 [0 0 0 1 0]
 [0 0 0 0 1]]


35

## Example 3 - 2018-2019 Contest 4 - Intermeidate
Problem 1

In [15]:
m1 = np.matrix([[1,1,1],
                [1,0,0],
                [1,1,1]])
m1

matrix([[1, 1, 1],
        [1, 0, 0],
        [1, 1, 1]])

In [16]:
m3 = m1*m1*m1
m3

matrix([[7, 5, 5],
        [3, 2, 2],
        [7, 5, 5]])

In [17]:
np.sum(m3)

41

In [2]:
a = np.matrix([[1, 0, 0,1], 
              [0,1,1,0],
              [1,0,1,0],
              [0,0,1,1]])

In [3]:
a

matrix([[1, 0, 0, 1],
        [0, 1, 1, 0],
        [1, 0, 1, 0],
        [0, 0, 1, 1]])

In [4]:
a2 = a*a
a2

matrix([[1, 0, 1, 2],
        [1, 1, 2, 0],
        [2, 0, 1, 1],
        [1, 0, 2, 1]])

In [5]:
a3 = a2*a
a3


matrix([[2, 0, 3, 3],
        [3, 1, 3, 1],
        [3, 0, 2, 3],
        [3, 0, 3, 2]])

In [6]:
aa = a^2
aa

matrix([[3, 2, 2, 3],
        [2, 3, 3, 2],
        [3, 2, 3, 2],
        [2, 2, 3, 3]], dtype=int32)

In [7]:
aa2 = a*a.T
aa2

matrix([[2, 0, 1, 1],
        [0, 2, 1, 1],
        [1, 1, 2, 1],
        [1, 1, 1, 2]])