# Python Tutorials: Matrix Operations with Numpy

### Author: Dr. Owen Chen

### Date: 2023 Fall

The easy way to conduct matrix operations in Python is to use Numpy!

**NumPy** is an open-source Python library that we can use to perform high-level mathematical operations with arrays, matrices and linear algebra.

The numpy array is a data structure representing multidimension arrays which is optimized for both memory and performance.


In [1]:
#Install Numpy:
!pip install numpy

In [2]:
import numpy as np

## One dimention array in Numpy

In [104]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

## Two dimension array - Matrix

In [105]:
mat = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Create a numpy array from a list of lists

In [ ]:
import numpy as np
list_of_lists = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

np_array = np.array(list_of_lists)

np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Initialize an array of zeros

In [ ]:
zeros_array = np.zeros( (4, 5) )
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Initialize and array of ones

In [ ]:
ones_array = np.ones( (6, 6) )
ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Using arrange

In [ ]:
nine = np.arange( 9 )
nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Using reshape

In [ ]:
nine.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Introspection

#### Get the data type

In [ ]:
np_array.dtype

dtype('int64')

#### Get the array's shape

In [ ]:
np_array.shape

(4, 4)

#### Get the number of items in the array

In [ ]:
np_array.size

16

#### Get the size of the array in bytes

In [ ]:
np_array.nbytes

128

### Setting the data type

#### dtype parameter

In [ ]:
np_array = np.array(list_of_lists, dtype=np.int8)
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

#### Size reduction

In [ ]:
np_array.nbytes

16

#### The data type setting is immutible 
Data may be truncated if the data type is restrictive.

In [ ]:
np_array[0][0] = 1.7344567
np_array[0][0]

1

### Array Slicing


*   Slicing can be used to get a view reprsenting a sub-array. 
*   The slice is a view to the original array, the data is not copied to a new data structure
*   The slice is taken in the form: array[ rows, columns ]






In [ ]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [ ]:
np_array[2:, :3]

array([[ 9, 10, 11],
       [13, 14, 15]], dtype=int8)

### Math operations


*   Unlike a unlike nested lists, matrix operations perform mathimatical operations on data



#### Create two 3 x 3 arrays

In [ ]:
np_array_1 = np.arange(9).reshape(3,3)
np_array_1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np_array_2 = np.arange(10, 19).reshape(3,3)
np_array_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### Multiply the arrays

In [ ]:
np_array_1 * np_array_2

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

#### Add the arrays

In [ ]:
np_array_1 + np_array_2

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

### Matrix operations

#### Transpose

In [ ]:
np_array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]], dtype=int8)

#### Dot product

In [ ]:
np_array_1.dot(np_array_2)


array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

## Use np.matrix to define a matrix

In [57]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 3-dimension array

In [18]:
d = np.array([[[111, 112, 113], [124, 125, 126]], [[211, 212, 213], [224, 225, 226]], [[311, 312, 313], [324, 325, 326]]])
d

array([[[111, 112, 113],
        [124, 125, 126]],

       [[211, 212, 213],
        [224, 225, 226]],

       [[311, 312, 313],
        [324, 325, 326]]])

## Check dimenion - ndim

In [27]:
print(arr.ndim)
print(mat.ndim)
print(d.ndim)

1
2
3


## NumPy Array Indexing

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [10]:
print(f"First element of arr: {arr[0]}")
print(f"Last element of arr: {arr[-1]}")

First element of arr: 1
Last element of arr: 5


In [106]:
print(f"First row of mat: {mat[0]}")
print(f"Last row of mat: {mat[-1]}")

First row of mat: [1 2 3]
Last row of mat: [7 8 9]


In [107]:
print(f"First col of mat: {mat[:,0]}")
print(f"Last colof mat: {mat[:,-1]}")

First col of mat: [1 4 7]
Last colof mat: [3 6 9]


In [30]:
# First element - 0,0
mat[0,0]

1

In [31]:
# Element on row i, col j
i, j = 1, 2
mat[i,j]

6

## NumPy Matrix Indexing

In [59]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

In [65]:
# First element - 0,0
mat1[0,0]

1

In [60]:
print(f"First row of mat1: {mat1[0]}")
print(f"Last row of mat1: {mat1[-1]}")

First row of mat1: [[1 2 3]]
Last row of mat1: [[7 8 9]]


In [64]:
print(f"First col of mat1: {mat1[:,0]}")
print(f"Last col of mat1: {mat1[:,-1]}")

First col of mat1: [[1]
 [4]
 [7]]
Last col of mat1: [[3]
 [6]
 [9]]


In [62]:
mat1.shape

(3, 3)

## 3 dimensions - use 3 indices

In [21]:
print(f"First element of first dimenion of d: {d[0]}")
print(f"Last element of first dimenion of d: {d[-1]}")

First element of first dimenion of d: [[111 112 113]
 [124 125 126]]
Last element of first dimenion of d: [[311 312 313]
 [324 325 326]]


In [20]:
print(f"First element of first dimenion of d: {d[0,:,:]}")
print(f"Last element of first dimenion of d: {d[-1,:,:]}")

First element of first dimenion of d: [[111 112 113]
 [124 125 126]]
Last element of first dimenion of d: [[311 312 313]
 [324 325 326]]


In [22]:
print(f"First element of 2nd dimenion of d: {d[:,0,:]}")
print(f"Last element of 2nd dimenion of d: {d[:, -1, :]}")

First element of 2nd dimenion of d: [[111 112 113]
 [211 212 213]
 [311 312 313]]
Last element of 2nd dimenion of d: [[124 125 126]
 [224 225 226]
 [324 325 326]]


In [23]:
print(f"First element of 3rd dimenion of d: {d[:,:,0]}")
print(f"Last element of 3rd dimenion of d: {d[:, :, -1]}")

First element of 3rd dimenion of d: [[111 124]
 [211 224]
 [311 324]]
Last element of 3rd dimenion of d: [[113 126]
 [213 226]
 [313 326]]


## Matrix addition - two matrices must have the same shapes

In [66]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
mat2 = np.matrix([[1, 2, 3], [4, 5, 6]])

In [67]:
# can not add two matrices with different dimensions
# This will give an error below
mat3 = mat1 + mat2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [74]:
mat2 = np.matrix([[2, 2, 2], [2, 2, 2],[2, 2, 2]])
mat3 = mat1 + mat2
mat3

matrix([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

## Matrix subtractin - two matrices must have the same shapes

In [75]:
mat3 = mat1 - mat2
mat3

matrix([[-1,  0,  1],
        [ 2,  3,  4],
        [ 5,  6,  7]])

## Matrix multiplications

- \* or np.matmul or np.dot() for matrix product or dot product

- np.multiply() for element-wise product of two matrices


### Matrix Product - Method 1  operator \*

In [77]:
mat3 = mat1 * mat2
mat3

matrix([[12, 12, 12],
        [30, 30, 30],
        [48, 48, 48]])

### Matrix Product - Method 2  np.matmul()

In [81]:
mat3 = np.matmul(mat1, mat2)
mat3

matrix([[12, 12, 12],
        [30, 30, 30],
        [48, 48, 48]])

### Matrix Product - Method 3  np.dot()

In [82]:
mat3 = np.dot(mat1, mat2)
mat3

matrix([[12, 12, 12],
        [30, 30, 30],
        [48, 48, 48]])

### Element-wide multiplication

In [78]:
mat3 = np.multiply(mat1, mat2)
mat3

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [41]:
mat4 = np.array([[1, 0, 0], [0, 1, 0],[0, 0, 1]])
mat5 = mat1 * mat4
mat5

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

## Matrix Square

In [94]:
matsq = mat1 * mat1
matsq

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [95]:
mat3 = np.matmul(mat1, mat1)
mat3

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

## Element-wise square

In [88]:
mat3 = np.square(mat1)
mat3

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

## Grah Theory - Adjacency Matrix

### Calculate number of different paths

### Problem 2: Find the total number of different paths from A to C of lenght 2 or 4

In [91]:
m1 = np.matrix([[1,0,1],[0,1,1],[1,0,0]])
m1

matrix([[1, 0, 1],
        [0, 1, 1],
        [1, 0, 0]])

In [96]:
m2 = m1*m1
m2

matrix([[2, 0, 1],
        [1, 1, 1],
        [1, 0, 1]])

In [97]:
m4 = m2*m2
m4

matrix([[5, 0, 3],
        [4, 1, 3],
        [3, 0, 2]])

### 2018-2019 ACSL Contest #4 - Problem 2
How many paths of length 2 

In [102]:
m = np.matrix([[0, 1, 0, 1, 1],
               [0, 0, 1, 0, 1],
               [1, 1, 0, 1, 0],
               [0, 0, 0, 0, 1],
               [0, 0, 0, 1, 0]])
m

matrix([[0, 1, 0, 1, 1],
        [0, 0, 1, 0, 1],
        [1, 1, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0]])

In [103]:
m2 = m*m
m2

matrix([[0, 0, 1, 1, 2],
        [1, 1, 0, 2, 0],
        [0, 1, 1, 1, 3],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])